#server:
#  port: 9301



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_blog?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      generate-ddl: true

      database:
        platform: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level:
      root: info
      com.ais: debug
      file: log/blog-dev.log



